### ISSUE TITLE
Remove more C++ remnants

### ISSUE THREAD

**Issue by perlun** [chaos4ever/chaos#28]
The `C_EXTERN_BEGIN` etc. in `include/storm/defines.h`. Should be done away with so can completely erase the C++ traces.

**Comment by perlun** [comment]
(The header files in the libraries also need to be adjusted to reflect this.)

But wait a minute? Maybe we should keep this? I mean, I think this is needed to support being able to use our header files and stuff from C++ programs, and I don't really see that we need to *forbid* or complicate that. Even though we won't convert the  `storm` kernel etc (like has been discussed before), we still can allow people to use chaos from C++.

Comments, @johannesl?

**Comment by johannesl** [comment]
You are completely right here. We should not complicate building programs in C++.

**Comment by perlun** [comment]
Alright. Let's make it a done deal then.
