### ISSUE TITLE
Support gcc-7

### ISSUE THREAD

**Issue by perlun** [chaos4ever/chaos#83]
It's apparently included in `stretch` since a while back: https://packages.debian.org/stretch/gcc-6

We should use and support it, since we rely on `stretch` for our Vagrant box anyway.

**Comment by perlun** [comment]
Since this issue was created, gcc-7 has been released: https://packages.debian.org/buster/gcc-7

We should probably skip gcc 6 and go straight for gcc-7 (or if we like and have energy, support them both).

**Comment by CaspecoHenrik** [comment]
Clang!

---
Henrik Doverhill
Ägare och produktchef, Caspeco AB
________________________________

**Comment by perlun** [comment]
Already registered - #90. 😄 

Will you do it? 😉
